apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploydesafio2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: hilroq/conversao-temperatura:latest
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: service-web
spec:
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30000
  type: NodePort